apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  labels:
    app: my-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
        name: my-application
    spec:
      containers:
        - name: app-v1
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: my-application-service
spec:
  type: NodePort
  selector:
    name: my-application
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30080
